import { Building2, MapPin, User } from "lucide-react";

export const FIELD_LABELS = {
  firstName: "First Name",
  lastName: "Last Name",
  email: "Email",
  phoneNumber: "Phone Number",
  businessName: "Business Name",
  registrationNumber: "Registration Number",
  country: "Country",
  state: "State",
  city: "City",
  address: "Address",
  postalCode: "Postal Code",

  // Buyer
  buyersCompanyName: "Company Name",
  registrationNumber: "Registration Number",
  taxId: "Tax ID",
  contactName: "Contact Name",
  contactEmail: "Contact Email",
  countryCode: "Country Code",
  contactPhone: "Contact Phone",

  status: "Status",
  isVerified: "Verified",
  isDeleted: "Deleted",
  isApproved: "Approved",
};

export const HIDDEN_FIELDS = [
  "id",
  "userId",
  "ownerId",
  "planId",
  // "createdAt",
  // "updatedAt",
  // "is_deleted",
  // "is_verified",
  // "is_approved",
  // "isDeleted",
  // "isVerified",
  // "isApproved",
];

export const ROLE_CONFIG = {
  business_owner: {
    API_TO_UI: {
      first_name: "firstName",
      last_name: "lastName",
      email: "email",
      phoneNumber: "phoneNumber",
      businessName: "businessName",
      registrationNumber: "registrationNumber",
      country: "country",
      state: "state",
      city: "city",
      address: "address",
      postalCode: "postalCode",
      status: "status",
      is_verified: "isVerified",
      is_deleted: "isDeleted",
      is_approved: "isApproved",
    },
    UI_TO_API: {
      firstName: "first_name",
      lastName: "last_name",
      email: "email",
      phoneNumber: "phoneNumber",
      businessName: "businessName",
      registrationNumber: "registrationNumber",
      country: "country",
      state: "state",
      city: "city",
      address: "address",
      postalCode: "postalCode",
      status: "status",
      isVerified: "is_verified",
      isDeleted: "is_deleted",
      isApproved: "is_approved",
    },
    sections: {
      business: {
        title: "Business Details",
        icon: Building2,
        fields: [
          "businessName",
          "registrationNumber",
          "firstName",
          "lastName",
          "email",
          "phoneNumber",
        ],
      },
      location: {
        title: "Location",
        icon: MapPin,
        fields: ["address", "city", "state", "country", "postalCode"],
      },
      statusSection: {
        title: "Status",
        icon: User,
        fields: ["status", "isVerified", "isDeleted", "isApproved"],
      },
    },
  },

  super_admin: {
    API_TO_UI: {
      buyers_company_name: "buyersCompanyName",
      buyersCompanyName: "buyersCompanyName",
      registration_number: "registrationNumber",
      registrationNumber: "registrationNumber",
      tax_id: "taxId",
      taxId: "taxId",
      contact_name: "contactName",
      contactName: "contactName",
      contact_email: "contactEmail",
      contactEmail: "contactEmail",
      country_code: "countryCode",
      countryCode: "countryCode",
      contact_phone: "contactPhone",
      contactPhone: "contactPhone",
      country: "country",
      state: "state",
      city: "city",
      address: "address",
      postal_code: "postalCode",
      postalCode: "postalCode",
      status: "status",
      is_verified: "isVerified",
      is_deleted: "isDeleted",
    },
    UI_TO_API: {
      buyersCompanyName: "buyers_company_name",
      registrationNumber: "registration_number",
      taxId: "tax_id",
      contactName: "contact_name",
      contactEmail: "contact_email",
      contactPhone: "contact_phone",
      countryCode: "country_code",
      country: "country",
      state: "state",
      city: "city",
      address: "address",
      postalCode: "postal_code",
      status: "status",
      isVerified: "is_verified",
      isDeleted: "is_deleted",
    },
    sections: {
      business: {
        title: "Company Details",
        icon: Building2,
        fields: [
          "buyersCompanyName",
          "registrationNumber",
          "taxId",
          "contactName",
          "contactEmail",
          "contactPhone",
          "countryCode",
        ],
      },
      location: {
        title: "Location",
        icon: MapPin,
        fields: ["address", "city", "state", "country", "postalCode"],
      },
      statusSection: {
        title: "Status",
        icon: User,
        fields: ["status", "isVerified", "isDeleted"],
      },
    },
  },
};
